language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-migmar97
  api_key:
    secure: Tn4om/8HWP4MnJf43rguhPzticWbw3bm4UQ0lQzWtRnJk6SYj9D4jyqPuNm19uJ9PqB0XOIMS7gqWw4LFWOs6b/3nf01uPUb56bn3EOnVEZFGCDS3CqE+ZGsWNoVLwJGP47MtAvfr52xf5s3Y5axPxjdxCVhbdv1fFYA8PPiP2OuYSe2WvhodwOFN1bDygW1Mv1sso23jyZUz/aHPoVaDfCdCATkDXx6RXaLoL0jXQPHa5Cn7bDJX+5H0JAZd/u3/FEK6uJ3NNNmMLqwgBPsll8lJnZ7mch+ij83eufg2BNacMjBjLDpNYeszCG8AUFQGaeer9O6mNPAYdYKy9OouD+sYmBI2u/khdmJwvDQqNSZ8wNidox0EZy8G/+FDJaW/ADaSvBZUg1dG9grm5nVhE7Z0LCnVbYTqCxF6+P99OsOKJslbOjApSX9udH3dj/my0MGa2LpgmquSKT4o4lwwmvR+CaJBshaqF0H/XMK8yPEqxCS6rymZ/UXnOlgu4kA+ock8ez2Wza3SEwvVMZyq1QZf41yaRA0xzUefMdXfve/grOQcXYi5glEp8Dvui1AZAghG4LBFddqs/J2ZKSI4FD0oGGJohHo7i+8cSjsuDWU4phDUXTlKJPaLvstguwow5744vEbGjH23nz/7Xy5wBsXwhqpX5ktuThkNo1c10Q=
